#!/bin/bash

set -e

POSTGRES="psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

echo "Config database: ${DB_NAME}"

$POSTGRES <<EOSQL
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};

DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA IF NOT EXISTS ${DB_APP_SCHEMA} AUTHORIZATION ${POSTGRES_USER};
EOSQL
